[versions]
agp = "8.3.0"
kotlin = "1.9.22"
kotlinxCoroutines = "1.8.0"
kotlinxSerializationJson = "1.6.3"
kotlinxDateTime = "0.6.0-RC.2"

androidxActivity = "1.8.2"
androidxDataStore = "1.0.0"
androidxLifecycle = "2.7.0"
androidxRoom = "2.6.1"

assertk = "0.28.0"
desugarJdkLibs = "2.0.4"
detekt = "1.23.5"

firebaseAnalytics = "21.5.1"
firebaseAuth = "22.3.1"
firebaseConfig = "21.6.2"
firebaseCrashlytics = "18.6.2"
firebaseFirestore = "24.10.3"

junit = "5.10.2"
kermit = "2.0.3"
ktor = "3.0.0-beta-1"
mockK = "1.13.10"
okhttp = "4.12.0"
okio = "3.8.0"
versionsGradlePlugin = "0.51.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-datastorePrefs = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDataStore" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "androidxRoom" }

assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }

# Firebase - https://firebase.google.com/support/release-notes/android
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalytics" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
google-firebase-config = { module = "com.google.firebase:firebase-config", version.ref = "firebaseConfig" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
google-firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore"  }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

mockK = { module = "io.mockk:mockk", version.ref = "mockK" }

gradleVersions-gradlePluginClasspath = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsGradlePlugin" }
